### ISSUE TITLE
Gnome Settings Integration

### ISSUE THREAD

**Issue by ChappIO** [ChappIO/dashfiles#1]
It would be good to have native support for gsettings.

I would see this implemented through a `gsettings.yaml` file where you can specify your settings. 

Example: Set your gnome theme to 'Numix-Frost'
```yaml
org:
  gnome:
    desktop:
        interface:
            gtk-theme: 'Numix-Frost'
```
